{{- if .Values.awsCredentials.accessKeyId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-credentials
  labels:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey | quote }}
{{- end }}
