{{- if and .Values.webDb.enabled .Values.webDb.pgbackrest.enabled -}}
{{- $p := .Values.webDb.pgbackrest -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-db-pgbackrest
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-db
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
stringData:
  pgbackrest.conf: |
    [global]
    compress-type=zst
    lock-path=/tmp/pgbackrest
    log-level-file=off
    repo1-type=s3
    repo1-path={{ $p.s3Path }}
    repo1-block=y
    repo1-bundle=y
    repo1-retention-full={{ $p.retentionFull }}
    repo1-s3-bucket={{ $p.s3Bucket }}
    repo1-s3-endpoint={{ $p.s3Endpoint }}
    repo1-s3-region={{ $p.s3Region }}
    repo1-s3-key-type={{ $p.s3KeyType }}
    {{- if $p.s3Key }}
    repo1-s3-key={{ $p.s3Key }}
    repo1-s3-key-secret={{ $p.s3KeySecret }}
    {{- end }}
    {{- if $p.cipherPass }}
    repo1-cipher-type=aes-256-cbc
    repo1-cipher-pass={{ $p.cipherPass }}
    {{- end }}
    {{- if $p.archivePushQueueMax }}
    archive-push-queue-max={{ $p.archivePushQueueMax }}
    {{- end }}

    [main]
    pg1-path={{ .Values.webDb.env.PGDATA }}
{{- end }}
